### ISSUE TITLE
The 'en16931' package was not installed in a way that PackageLoader understands

### ISSUE THREAD

**Issue by maikelmertens** [invinet/python-en16931#7]
I've stumbled upon an issue with using this library, when I try to import this library, more specifically with `from en16931 import Invoice`, it will yield an error:

```
Traceback (most recent call last):
  File "/home/x/app.py", line 1, in <module>
    from en16931 import Invoice
  File "/home/x/.venv/lib/python3.10/site-packages/en16931/__init__.py", line 12, in <module>
    from en16931.invoice import Invoice
  File "/home/x/.venv/lib/python3.10/site-packages/en16931/invoice.py", line 21, in <module>
    templates = Environment(loader=PackageLoader('en16931', 'templates'))
  File "/home/x/.venv/lib/python3.10/site-packages/jinja2/loaders.py", line 323, in __init__
    raise ValueError(
ValueError: The 'en16931' package was not installed in a way that PackageLoader understands.
```

Searching on internet, the problem seem to be related to jinja and packaging data. Any help in order to resolve this, is appreciated.

**Comment by mcmihai** [comment]
it can't find the template. if you were to copy the templates directory from this repo to "/home/x/.venv/lib/python3.10/site-packages/en16931/" it would work.

**Comment by jtorrents** [comment]
I'll take a deeper look at Jinja docs tomorrow. I'm sure I'm missing something obvious.  I thought the problem was resolved because installing with pip for development:

```
$ pip install -e ~/projects/python-en16931
``` 

Does not raise the error.

**Comment by maikelmertens** [comment]
The solution @mcmihai provided indeed solved the issue. I've created a small PR to add the templates directory and to automatically install the dependencies while installing this package: https://github.com/invinet/python-en16931/pull/8

**Comment by jtorrents** [comment]
Thanks @maikelmertens! I merged your pull request and deployed a new version 0.1.3 to pypi:

https://pypi.org/project/en16931/0.1.3/

Now we are able to find the templates after installation as @mcmihai indicated.

**Comment by maikelmertens** [comment]
The version `0.1.3` works like a charm now, no issues in using this package. Thank you too @jtorrents and @mcmihai!
